"""
Standardized data schemas for the SMB trading bot.
"""

from __future__ import annotations
from dataclasses import dataclass
from typing import Literal, Optional
import pandas as pd


@dataclass
class Trade:
    """Single trade from exchange feed or historical data."""
    timestamp: int  # nanoseconds since epoch
    symbol: str
    price: float
    size: float
    side: Literal["b", "s"]  # buy/sell


@dataclass
class Bar:
    """OHLCV bar (candle) for a given time interval."""
    timestamp: int  # end of interval, nanoseconds
    symbol: str
    open: float
    high: float
    low: float
    close: float
    volume: float
    
    @classmethod
    def from_df_row(cls, row: pd.Series) -> "Bar":
        """Create Bar from a pandas Series row."""
        return cls(
            timestamp=row.timestamp,
            symbol=row.symbol,
            open=row.open,
            high=row.high,
            low=row.low,
            close=row.close,
            volume=row.volume,
        )


@dataclass
class Signal:
    """Trading signal generated by strategy."""
    timestamp: int
    symbol: str
    action: Literal["buy", "sell", "hold"]
    price: float
    size: Optional[float] = None
    reason: Optional[str] = None
